# Generated by Django 4.2.1 on 2023-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='my_text',
            field=models.TextField(default=''),
        ),
    ]
