# Generated by Django 4.2.1 on 2023-05-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0002_mymodel_my_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='my_text',
            new_name='about_my_self',
        ),
    ]
