# Generated by Django 4.2.1 on 2023-05-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0003_rename_my_text_mymodel_about_my_self'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myModel',
            new_name='about',
        ),
    ]
