# Generated by Django 4.2.1 on 2023-05-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0005_tahun_pendidikan_1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tahun_pendidikan_1',
            new_name='tahun_pendidikan_satu',
        ),
    ]
