# Generated by Django 4.2.1 on 2023-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0008_rename_tahun_pendidikan_satu_tahun_pendidikan_satu_tahun_pendidikan_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='tahun_pendidikan_satu',
            name='sekolah_pendidikan_1',
            field=models.TextField(default=''),
        ),
    ]
