# Generated by Django 4.2.1 on 2023-05-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0011_tahun_pendidikan_empat_tahun_pendidikan_tiga'),
    ]

    operations = [
        migrations.CreateModel(
            name='pekerjaan_kedua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan_2_tahun', models.TextField(default='')),
                ('pekerjaan_2', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='pekerjaan_keempat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan_4_tahun', models.TextField(default='')),
                ('pekerjaan_4', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='pekerjaan_ketiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan_3_tahun', models.TextField(default='')),
                ('pekerjaan_3', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='pekerjaan_pertama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pekerjaan_1_tahun', models.TextField(default='')),
                ('pekerjaan_1', models.TextField(default='')),
            ],
        ),
    ]
