# Generated by Django 4.2.1 on 2023-05-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0012_pekerjaan_kedua_pekerjaan_keempat_pekerjaan_ketiga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pekerjaan_kedua',
            old_name='pekerjaan_2_tahun',
            new_name='pekerjaan_tahun_2',
        ),
        migrations.RenameField(
            model_name='pekerjaan_keempat',
            old_name='pekerjaan_4_tahun',
            new_name='pekerjaan_tahun_4',
        ),
        migrations.RenameField(
            model_name='pekerjaan_ketiga',
            old_name='pekerjaan_3_tahun',
            new_name='pekerjaan_tahun_3',
        ),
        migrations.RenameField(
            model_name='pekerjaan_pertama',
            old_name='pekerjaan_1_tahun',
            new_name='pekerjaan_tahun_1',
        ),
    ]
