# Generated by Django 4.2.1 on 2023-05-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0014_remove_pekerjaan_keempat_pekerjaan_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='pekerjaan_keempat',
            name='pekerjaan_4',
            field=models.TextField(default=''),
        ),
    ]
