# Generated by Django 4.2.1 on 2023-05-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0015_pekerjaan_keempat_pekerjaan_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_hp', models.TextField(default='')),
                ('email', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestasi_1', models.TextField(default='')),
                ('prestasi_2', models.TextField(default='')),
                ('prestasi_3', models.TextField(default='')),
                ('prestasi_4', models.TextField(default='')),
                ('prestasi_5', models.TextField(default='')),
                ('prestasi_6', models.TextField(default='')),
                ('prestasi_7', models.TextField(default='')),
                ('prestasi_8', models.TextField(default='')),
                ('prestasi_9', models.TextField(default='')),
                ('prestasi_10', models.TextField(default='')),
            ],
        ),
    ]
