# Generated by Django 4.2.1 on 2023-05-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0016_kontak_prestasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kontak',
            old_name='no_hp',
            new_name='nomor',
        ),
    ]
