# Generated by Django 4.2.1 on 2023-05-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat_hidup', '0017_rename_no_hp_kontak_nomor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestasi',
            name='prestasi_1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prestasi_10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prestasi_2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prestasi_3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prestasi_4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prestasi_5',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prestasi_6',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prestasi_7',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prestasi_8',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prestasi_9',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
