# Generated by Django 4.2.1 on 2023-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran_sosial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='sub_materi',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
