# Generated by Django 4.2.1 on 2023-05-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran_sosial', '0002_materi_sub_materi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materi',
            name='sub_materi',
        ),
    ]
