# Generated by Django 4.2.1 on 2023-05-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filosofi_pendidikan_indonesia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materi',
            old_name='materi',
            new_name='judul_materi',
        ),
    ]
