# Generated by Django 4.2.1 on 2023-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filosofi_pendidikan_indonesia', '0003_rename_judul_materi_materi_materi'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_materi_pertama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_materi_1', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
