# Generated by Django 4.2.1 on 2023-05-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filosofi_pendidikan_indonesia', '0005_text_materi_kedua_text_materi_ketiga'),
    ]

    operations = [
        migrations.CreateModel(
            name='gambar_pertama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_1', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
