# Generated by Django 4.2.1 on 2023-05-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filosofi_pendidikan_indonesia', '0008_remove_gambar_pertama_gambar_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='gambar_kedua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_2', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
